import "./globals.css";
import { Inter } from "next/font/google";
import Navbaar from "./Componnents/nav-baar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BookSnap",
  description: "Generated by Abhishek Kumar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbaar />
        {children}
      </body>
    </html>
  );
}
